language: ruby
rvm:
  - 2.0.0
env:
  - DB=sqlite
script:
  - cd ror/railsdoc
  - gem install xpath -v '2.0.0'
  - bundle install
  - rake db:test:load
  - bundle exec rspec ./spec/helpers/users_helper_spec.rb
  - bundle exec rspec ./spec/models/user_spec.rb
  - bundle exec rspec ./spec/models/users_spec.rb
  - bundle exec rspec ./spec/helpers/blogs_helper_spec.rb
  - bundle exec rspec ./spec/models/blog_spec.rb 