language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ruby-head
  - jruby-head
  - 1.8.7
  - ree
env:
  - DB=sqlite3
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - bundle exec rspec spec